networks:
  frontend:
  backend:

volumes:
  mysql_db:
  mysql_log:
  nginx_log:
  topsserver_data:

services:

  mirth-connect:
    build: mirth-connect
    image: fabrom/mirth-connect
    container_name: mc-mirthconnect
    restart: on-failure
    volumes:
      - "./mirth-connect/conf/log4j2.properties:/opt/mirth-connect/conf/log4j2.properties:rw"
      - "./mirth-connect/conf/mirth.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/mirth-connect/conf/dbdrivers.xml:/opt/mirth-connect/conf/dbdrivers.xml:rw"
      - "./data/mirth-connect/custom-lib/:/opt/mirth-connect/custom-lib/:ro"
      - "./data/mirth-connect/spools/:/var/spool/mirth/:rw"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - frontend
      - backend
    depends_on:
      - mirth-database
      - rp-https

  phpmyadmin:
    container_name: mc-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    ports:
      - "127.0.0.1:8181:80"
    environment:
      - "PMA_HOST=mirth-database"
      - "MYSQL_ROOT_PASSWORD=password"
    networks:
      - frontend
      - backend
    depends_on:
      - mirth-database

  mirth-database:
    container_name: mc-mysql
    hostname: mysql
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M
    restart: on-failure
    volumes:
      - "mysql_db:/var/lib/mysql"
      - "mysql_log:/var/log/mysql"
    environment:
      - "MYSQL_DATABASE=mirth-test"
      - "MYSQL_USER=mirth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    networks:
      - backend

  rp-https:
    container_name: mc-rp-https
    hostname: rp-https
    image: nginx:latest
    restart: on-failure
    ports:
      - "7980:7980"
    volumes:
      - "./data/rp-https/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data/rp-https/conf/nginx/conf.d/:/etc/nginx/conf.d/:ro"
      - "./data/rp-https/conf/ssl/:/etc/ssl/private/:ro"
      - "nginx_log:/var/log/nginx"
    networks:
      - backend

  topsserver-mock:
    container_name: mc-topsserver-mock
    image: cr.medoco.health/medoco/tops-server-mock:latest
    hostname: topsserver-mock
    restart: no
    environment:
      POSTGRES_PASSWORD: example
      PGHOST: /tmp # Emulating macOS installation with unix socket in /tmp. This will not set the server, but will be used by the scripts inside the container.
    ports:
      - "5432:5432"
      - "2222:22"
    networks:
      - frontend
    # volumes:
      # !! For some unknown reason, you must use the actual PG_DATA folder,
      # which, by default, is the data/ subfolder. If you map the parent
      # postgresql folder, the docker will not persist, and it will save data
      # inside the container instead of the volume
      # - topsserver_data:/var/lib/postgresql/data
